AWSTemplateFormatVersion: 2010-09-09

Parameters:
    UserPoolName:
        Default: MyUserPool
        Type: String
    UserPoolDomain:
        Default: test-123456789012
        Type: String
    ClientId:
        Default: my-client-id
        Type: String
    ClientSecret:
        Default: rlO/K1kL/nqFR3gPvuWPYNc+WZtgAl4EBi41RMHwQvFV
        Type: String
    IdentityProviderName:
        Default: MyIdP
        Type: String
    OidcIssuer:
        Default: https://idp.example.com
        Type: String

Resources:
    UserPool:
        Type: AWS::Cognito::UserPool
        Properties:
            UserPoolName: !Ref UserPoolName
            AdminCreateUserConfig:
                AllowAdminCreateUserOnly: false
                UnusedAccountValidityDays: 7
            AliasAttributes: []
            AutoVerifiedAttributes:
              - email
            DeviceConfiguration:
                ChallengeRequiredOnNewDevice: false
                DeviceOnlyRememberedOnUserPrompt: false
            EmailConfiguration:
                EmailSendingAccount:  COGNITO_DEFAULT
            Policies:
                PasswordPolicy:
                    MinimumLength: 8
                    RequireUppercase: true
                    RequireLowercase: true
                    RequireNumbers: true
                    RequireSymbols: false
            Schema:
              - Name: email
                Mutable: true
                Required: true
              - Name: family_name
                Mutable: true
                Required: true
              - Name: given_name
                Mutable: true
                Required: true

    UserPoolDomain:
        Type: AWS::Cognito::UserPoolDomain
        Properties: 
            Domain: !Ref UserPoolDomain
            UserPoolId: !Ref UserPool

    IdentityProvider:
        Type: AWS::Cognito::UserPoolIdentityProvider
        Properties: 
            ProviderName: !Ref IdentityProviderName
            AttributeMapping:
                email: EMAIL
                email_verified: EMAIL_VERIFIED
                given_name: GIVEN_NAME
                family_name: FAMILY_NAME
                username: sub
                name: USER_NAME
            ProviderDetails:
                client_id: !Ref ClientId
                client_secret: !Ref ClientSecret
                attributes_request_method: GET
                oidc_issuer: !Ref OidcIssuer
                authorize_scopes: openid
            ProviderType: OIDC
            UserPoolId: !Ref UserPool
